const PRODUCTS = {
  1: {
    id: 1,
    type: "glasses",
    name: "Aero Frame",
    price: "₹2,999",
    desc: "Ultra-light metal frame engineered for all-day comfort.",
    image: "assets/glass1.png",
    model: "./models/glass1.glb",
  },
  2: {
    id: 2,
    type: "glasses",
    name: "Urban Classic",
    price: "₹3,499",
    desc: "Matte black acetate with a timeless silhouette.",
    image: "assets/glass2.png",
    model: "./models/glass2.glb",
  },
  3: {
    id: 3,
    type: "watch",
    name: "Chrono Steel",
    price: "₹6,999",
    desc: "42mm stainless steel chronograph with sapphire glass.",
    image: "assets/watch1.png",
    model: "./models/watch1.glb",
  },
  4: {
    id: 4,
    type: "watch",
    name: "Minimal Leather",
    price: "₹5,499",
    desc: "Italian leather strap with a minimalist dial.",
    image: "assets/watch2.png",
    model: "./models/watch2.glb",
  },
};
